#!/bin/sh
PRG="$0"

while [ -h "$PRG" ]; do
	ls=`ls -ld "$PRG"`
	link=`expr "$ls" : '.*-> \(.*\)$'`
	if expr "$link" : '/.*' > /dev/null; then
		PRG="$link"
	else
		PRG=`dirname "$PRG"`/"$link"
	fi
done

PRGDIR=`dirname "$PRG"`
PRGDIR=`cd $PRGDIR/..;pwd`

go build github.com/leptonyu/goeast

if [ $? -ne 0 ]; then
	echo Build error!
	exit 201
fi

./goeast -init

rm goeast
